### ISSUE TITLE
setup.py should not import numpy directly

### ISSUE THREAD

**Issue by o-smirnov** [ddboline/shared-array#1]
The current setup.py script will fail on https://github.com/ddboline/shared-array/blob/master/setup.py#L22 if the system doesn't have ``numpy`` installed. 

As we're discussing [here](https://github.com/ratt-ru/CubiCal/pull/89#commitcomment-25805353), this is wrong -- setup should be able to tell pip to download and install numpy if it is not present.

**Comment by ddboline** [comment]
For future reference, this project is hosted at https://gitlab.com/tenzing/shared-array, this is an unmaintained fork.
